CREATE TABLE [dbo].[CHANGELISTDEFECTACTION] (
  [MainlineID] [numeric](10) NOT NULL,
  [ChangelistID] [numeric](10) NOT NULL,
  [DefectActionID] [numeric](10) NOT NULL,
  CONSTRAINT [PK_CHANGELISTDEFECTACTION] PRIMARY KEY CLUSTERED ([MainlineID], [ChangelistID], [DefectActionID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[CHANGELISTDEFECTACTION]
  ADD CONSTRAINT [CHANGELIST_CHGDEFACT] FOREIGN KEY ([MainlineID], [ChangelistID]) REFERENCES [dbo].[CHANGELIST] ([MainlineID], [ChangelistID])
GO

ALTER TABLE [dbo].[CHANGELISTDEFECTACTION]
  ADD CONSTRAINT [DEFECTACTION_CHGDEFACT] FOREIGN KEY ([MainlineID], [DefectActionID]) REFERENCES [dbo].[DEFECTACTION] ([MainlineID], [DefectActionID])
GO