CREATE TABLE [dbo].[CHANGELISTCODEREVIEW] (
  [MainlineID] [numeric](10) NOT NULL,
  [ReviewID] [numeric](10) NOT NULL,
  [ChangelistID] [numeric](10) NOT NULL,
  [ChangelistEventID] [numeric](10) NOT NULL,
  CONSTRAINT [PK_CHANGELISTCODEREVIEW] PRIMARY KEY CLUSTERED ([MainlineID], [ReviewID], [ChangelistID], [ChangelistEventID])
)
ON [PRIMARY]
GO

CREATE INDEX [IDX_CHANGELISTCODEREV_REVID]
  ON [dbo].[CHANGELISTCODEREVIEW] ([MainlineID], [ReviewID])
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[CHANGELISTCODEREVIEW]
  ADD CONSTRAINT [CODEREVIEW_CHANGELISTCODEREV] FOREIGN KEY ([MainlineID], [ReviewID]) REFERENCES [dbo].[CODEREVIEW] ([MainlineID], [ReviewID]) ON DELETE CASCADE
GO