CREATE TABLE [dbo].[Account] (
  [Id] [nvarchar](18) NOT NULL,
  [IsDeleted] [bit] NOT NULL,
  [MasterRecordId] [nvarchar](18) NULL,
  [Name] [nvarchar](255) NOT NULL,
  [Type] [nvarchar](255) NULL,
  [ParentId] [nvarchar](18) NULL,
  [BillingStreet] [nvarchar](255) NULL,
  [BillingCity] [nvarchar](40) NULL,
  [BillingState] [nvarchar](80) NULL,
  [BillingPostalCode] [nvarchar](20) NULL,
  [BillingCountry] [nvarchar](80) NULL,
  [BillingLatitude] [float] NULL,
  [BillingLongitude] [float] NULL,
  [BillingGeocodeAccuracy] [nvarchar](255) NULL,
  [BillingAddress] [ntext] NULL,
  [ShippingStreet] [nvarchar](255) NULL,
  [ShippingCity] [nvarchar](40) NULL,
  [ShippingState] [nvarchar](80) NULL,
  [ShippingPostalCode] [nvarchar](20) NULL,
  [ShippingCountry] [nvarchar](80) NULL,
  [ShippingLatitude] [float] NULL,
  [ShippingLongitude] [float] NULL,
  [ShippingGeocodeAccuracy] [nvarchar](255) NULL,
  [ShippingAddress] [ntext] NULL,
  [Phone] [nvarchar](40) NULL,
  [Fax] [nvarchar](40) NULL,
  [AccountNumber] [nvarchar](40) NULL,
  [Website] [nvarchar](255) NULL,
  [PhotoUrl] [nvarchar](255) NULL,
  [Sic] [nvarchar](20) NULL,
  [Industry] [nvarchar](255) NULL,
  [AnnualRevenue] [float] NULL,
  [NumberOfEmployees] [int] NULL,
  [Ownership] [nvarchar](255) NULL,
  [TickerSymbol] [nvarchar](20) NULL,
  [Description] [ntext] NULL,
  [Rating] [nvarchar](255) NULL,
  [Site] [nvarchar](80) NULL,
  [OwnerId] [nvarchar](18) NOT NULL,
  [CreatedDate] [datetime] NOT NULL,
  [CreatedById] [nvarchar](18) NOT NULL,
  [LastModifiedDate] [datetime] NOT NULL,
  [LastModifiedById] [nvarchar](18) NOT NULL,
  [SystemModstamp] [datetime] NOT NULL,
  [LastActivityDate] [datetime] NULL,
  [LastViewedDate] [datetime] NULL,
  [LastReferencedDate] [datetime] NULL,
  [Jigsaw] [nvarchar](20) NULL,
  [JigsawCompanyId] [nvarchar](20) NULL,
  [AccountSource] [nvarchar](255) NULL,
  [SicDesc] [nvarchar](80) NULL,
  [CustomerPriority__c] [nvarchar](255) NULL,
  [SLA__c] [nvarchar](255) NULL,
  [Active__c] [nvarchar](255) NULL,
  [CS_Zoho_Account_ID__c] [nvarchar](255) NULL,
  [UpsellOpportunity__c] [nvarchar](255) NULL,
  [SLASerialNumber__c] [nvarchar](10) NULL,
  [SLAExpirationDate__c] [datetime] NULL,
  [ExternalId__c] [nvarchar](5) NULL,
  [dddddddd7__c] [float] NULL,
  [wwwwww__c] [float] NULL,
  [Import2_Id__c] [nvarchar](255) NULL,
  [Group__c] [float] NULL,
  [SecondName__c] [nvarchar](27) NULL,
  [User_Listing_Count__c] [float] NULL,
  [TestName2__c] [nvarchar](12) NULL,
  [NumberofLocations__c] [float] NULL,
  [External3_number__c] [float] NULL,
  [TestConstant__c] [datetime] NULL,
  [External5_number__c] [float] NULL,
  [External3_text__c] [nvarchar](40) NULL,
  [External5_text__c] [nvarchar](40) NULL,
  [External6_text__c] [nvarchar](40) NULL,
  CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED ([Id])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO