CREATE TABLE [dbo].[Calendar] (
  [GIORNO] [int] NOT NULL,
  [MESE] [int] NOT NULL,
  [ANNO] [int] NOT NULL,
  [DESCRIZIONE] [varchar](40) NULL,
  [FLAG_FESTIVO] [int] NOT NULL,
  [FLAG_TURNI_MODIFICATI] [int] NOT NULL,
  [FLAG_TURNO_1_ATTIVO] [int] NOT NULL,
  [FLAG_TURNO_2_ATTIVO] [int] NOT NULL,
  [FLAG_TURNO_3_ATTIVO] [int] NOT NULL,
  [FLAG_TURNO_4_ATTIVO] [int] NOT NULL,
  [FLAG_TURNO_5_ATTIVO] [int] NOT NULL,
  [FLAG_TURNO_6_ATTIVO] [int] NOT NULL,
  PRIMARY KEY CLUSTERED ([GIORNO], [MESE], [ANNO])
)
ON [PRIMARY]
GO