CREATE TABLE [dbo].[BRANCHCREATION] (
  [MainlineID] [numeric](10) NOT NULL,
  [BranchID] [numeric](10) NOT NULL,
  [CreatorID] [numeric](10) NULL,
  [CreationType] [numeric](2) NULL,
  [idState] [numeric](10) NULL,
  [LabelID] [numeric](10) NULL,
  [DateCreatedBy] [datetime] NULL,
  CONSTRAINT [PK_BRANCHCREATION] PRIMARY KEY CLUSTERED ([MainlineID], [BranchID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[BRANCHCREATION]
  ADD CONSTRAINT [BRANCH_BRANCHCREATION] FOREIGN KEY ([MainlineID], [BranchID]) REFERENCES [dbo].[BRANCH] ([MainlineID], [BranchID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[BRANCHCREATION]
  ADD CONSTRAINT [LABEL_BRANCHCREATION] FOREIGN KEY ([MainlineID], [LabelID]) REFERENCES [dbo].[LABEL] ([MainlineID], [LabelID])
GO

ALTER TABLE [dbo].[BRANCHCREATION]
  ADD CONSTRAINT [SCMSTATES_BRANCHCREATION] FOREIGN KEY ([idState]) REFERENCES [dbo].[SCMSTATES] ([idState]) ON DELETE SET NULL
GO

ALTER TABLE [dbo].[BRANCHCREATION]
  ADD CONSTRAINT [SCMUSERS_BRANCHCREATION] FOREIGN KEY ([CreatorID]) REFERENCES [dbo].[SCMUSERS] ([idUser]) ON DELETE SET NULL
GO